"""Pydantic schemas package."""

from app.schemas.ingest import (
    MessageResponse,
    SMSIngestBatchRequest,
    SMSIngestBatchResponse,
    SMSIngestRequest,
    SMSIngestResponse,
)
from app.schemas.transaction import (
    ManualParseRequest,
    ManualParseResponse,
    ParsedTransaction,
    ReviewQueueItem,
    ReviewQueueResponse,
    TransactionDetailResponse,
    TransactionEvidenceResponse,
    TransactionFilterRequest,
    TransactionGroupListResponse,
    TransactionGroupResponse,
    TransactionNotesUpdate,
)
from app.schemas.wallet import (
    DashboardSummaryResponse,
    InstitutionListResponse,
    InstitutionResponse,
    InstrumentCreateRequest,
    InstrumentListResponse,
    InstrumentResponse,
    InstrumentUpdateRequest,
    WalletBalanceUpdateResponse,
    WalletCreateRequest,
    WalletInstrumentAttachRequest,
    WalletInstrumentDetachRequest,
    WalletInstrumentResponse,
    WalletListResponse,
    WalletResponse,
    WalletSummaryResponse,
    WalletUpdateRequest,
)

__all__ = [
    # Ingest
    "SMSIngestRequest",
    "SMSIngestBatchRequest",
    "SMSIngestResponse",
    "SMSIngestBatchResponse",
    "MessageResponse",
    # Transaction
    "ParsedTransaction",
    "TransactionGroupResponse",
    "TransactionGroupListResponse",
    "TransactionEvidenceResponse",
    "TransactionDetailResponse",
    "TransactionFilterRequest",
    "TransactionNotesUpdate",
    "ReviewQueueItem",
    "ReviewQueueResponse",
    "ManualParseRequest",
    "ManualParseResponse",
    # Wallet & Instruments
    "InstitutionResponse",
    "InstitutionListResponse",
    "InstrumentCreateRequest",
    "InstrumentUpdateRequest",
    "InstrumentResponse",
    "InstrumentListResponse",
    "WalletCreateRequest",
    "WalletUpdateRequest",
    "WalletInstrumentAttachRequest",
    "WalletInstrumentDetachRequest",
    "WalletInstrumentResponse",
    "WalletResponse",
    "WalletListResponse",
    "WalletBalanceUpdateResponse",
    "WalletSummaryResponse",
    "DashboardSummaryResponse",
]
