"""Pydantic schemas package."""

from app.schemas.analytics import (
    CategoryBreakdownResponse,
    CategorySpending,
    DailySpending,
    DashboardAnalyticsResponse,
    ExportRequest,
    MonthlyComparison,
    SpendingTimeSeriesResponse,
    TopVendorsResponse,
    VendorStats,
)
from app.schemas.auth import (
    ChangePasswordRequest,
    LoginRequest,
    RefreshRequest,
    RefreshResponse,
    TokenResponse,
    UserCreate,
    UserResponse,
)
from app.schemas.budget import (
    BudgetCreateRequest,
    BudgetListResponse,
    BudgetProgressResponse,
    BudgetResponse,
    BudgetSummaryResponse,
    BudgetUpdateRequest,
)
from app.schemas.ingest import (
    MessageResponse,
    SMSIngestBatchRequest,
    SMSIngestBatchResponse,
    SMSIngestRequest,
    SMSIngestResponse,
)
from app.schemas.report import (
    ReportDetailResponse,
    ReportGenerateRequest,
    ReportListResponse,
    ReportResponse,
)
from app.schemas.transaction import (
    ManualParseRequest,
    ManualParseResponse,
    ParsedTransaction,
    ReviewQueueItem,
    ReviewQueueResponse,
    TransactionDetailResponse,
    TransactionEvidenceResponse,
    TransactionFilterRequest,
    TransactionGroupListResponse,
    TransactionGroupResponse,
    TransactionNotesUpdate,
)
from app.schemas.wallet import (
    DashboardSummaryResponse,
    InstitutionListResponse,
    InstitutionResponse,
    InstrumentCreateRequest,
    InstrumentListResponse,
    InstrumentResponse,
    InstrumentUpdateRequest,
    WalletBalanceUpdateResponse,
    WalletCreateRequest,
    WalletInstrumentAttachRequest,
    WalletInstrumentDetachRequest,
    WalletInstrumentResponse,
    WalletListResponse,
    WalletResponse,
    WalletSummaryResponse,
    WalletUpdateRequest,
)

__all__ = [
    # Auth
    "LoginRequest",
    "TokenResponse",
    "RefreshRequest",
    "RefreshResponse",
    "UserResponse",
    "UserCreate",
    "ChangePasswordRequest",
    # Ingest
    "SMSIngestRequest",
    "SMSIngestBatchRequest",
    "SMSIngestResponse",
    "SMSIngestBatchResponse",
    "MessageResponse",
    # Transaction
    "ParsedTransaction",
    "TransactionGroupResponse",
    "TransactionGroupListResponse",
    "TransactionEvidenceResponse",
    "TransactionDetailResponse",
    "TransactionFilterRequest",
    "TransactionNotesUpdate",
    "ReviewQueueItem",
    "ReviewQueueResponse",
    "ManualParseRequest",
    "ManualParseResponse",
    # Wallet & Instruments
    "InstitutionResponse",
    "InstitutionListResponse",
    "InstrumentCreateRequest",
    "InstrumentUpdateRequest",
    "InstrumentResponse",
    "InstrumentListResponse",
    "WalletCreateRequest",
    "WalletUpdateRequest",
    "WalletInstrumentAttachRequest",
    "WalletInstrumentDetachRequest",
    "WalletInstrumentResponse",
    "WalletResponse",
    "WalletListResponse",
    "WalletBalanceUpdateResponse",
    "WalletSummaryResponse",
    "DashboardSummaryResponse",
    # Analytics
    "CategorySpending",
    "CategoryBreakdownResponse",
    "DailySpending",
    "SpendingTimeSeriesResponse",
    "VendorStats",
    "TopVendorsResponse",
    "MonthlyComparison",
    "DashboardAnalyticsResponse",
    "ExportRequest",
    # Budget
    "BudgetCreateRequest",
    "BudgetUpdateRequest",
    "BudgetResponse",
    "BudgetProgressResponse",
    "BudgetListResponse",
    "BudgetSummaryResponse",
    # Report
    "ReportGenerateRequest",
    "ReportResponse",
    "ReportDetailResponse",
    "ReportListResponse",
]
